// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// GrafanaListerExpansion allows custom methods to be added to
// GrafanaLister.
type GrafanaListerExpansion interface{}

// GrafanaNamespaceListerExpansion allows custom methods to be added to
// GrafanaNamespaceLister.
type GrafanaNamespaceListerExpansion interface{}

// GrafanaDashboardListerExpansion allows custom methods to be added to
// GrafanaDashboardLister.
type GrafanaDashboardListerExpansion interface{}

// GrafanaDashboardNamespaceListerExpansion allows custom methods to be added to
// GrafanaDashboardNamespaceLister.
type GrafanaDashboardNamespaceListerExpansion interface{}

// GrafanaDataSourceListerExpansion allows custom methods to be added to
// GrafanaDataSourceLister.
type GrafanaDataSourceListerExpansion interface{}

// GrafanaDataSourceNamespaceListerExpansion allows custom methods to be added to
// GrafanaDataSourceNamespaceLister.
type GrafanaDataSourceNamespaceListerExpansion interface{}

// GrafanaFolderListerExpansion allows custom methods to be added to
// GrafanaFolderLister.
type GrafanaFolderListerExpansion interface{}

// GrafanaFolderNamespaceListerExpansion allows custom methods to be added to
// GrafanaFolderNamespaceLister.
type GrafanaFolderNamespaceListerExpansion interface{}

// GrafanaNotificationChannelListerExpansion allows custom methods to be added to
// GrafanaNotificationChannelLister.
type GrafanaNotificationChannelListerExpansion interface{}

// GrafanaNotificationChannelNamespaceListerExpansion allows custom methods to be added to
// GrafanaNotificationChannelNamespaceLister.
type GrafanaNotificationChannelNamespaceListerExpansion interface{}
