// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	integreatlyv1alpha1 "github.com/scylladb/scylla-operator/pkg/externalapi/integreatly/v1alpha1"
	versioned "github.com/scylladb/scylla-operator/pkg/externalclient/integreatly/clientset/versioned"
	internalinterfaces "github.com/scylladb/scylla-operator/pkg/externalclient/integreatly/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/scylladb/scylla-operator/pkg/externalclient/integreatly/listers/integreatly/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GrafanaNotificationChannelInformer provides access to a shared informer and lister for
// GrafanaNotificationChannels.
type GrafanaNotificationChannelInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GrafanaNotificationChannelLister
}

type grafanaNotificationChannelInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGrafanaNotificationChannelInformer constructs a new informer for GrafanaNotificationChannel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGrafanaNotificationChannelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGrafanaNotificationChannelInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGrafanaNotificationChannelInformer constructs a new informer for GrafanaNotificationChannel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGrafanaNotificationChannelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IntegreatlyV1alpha1().GrafanaNotificationChannels(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IntegreatlyV1alpha1().GrafanaNotificationChannels(namespace).Watch(context.TODO(), options)
			},
		},
		&integreatlyv1alpha1.GrafanaNotificationChannel{},
		resyncPeriod,
		indexers,
	)
}

func (f *grafanaNotificationChannelInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGrafanaNotificationChannelInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *grafanaNotificationChannelInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&integreatlyv1alpha1.GrafanaNotificationChannel{}, f.defaultInformer)
}

func (f *grafanaNotificationChannelInformer) Lister() v1alpha1.GrafanaNotificationChannelLister {
	return v1alpha1.NewGrafanaNotificationChannelLister(f.Informer().GetIndexer())
}
