// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/scylladb/scylla-operator/pkg/externalclient/integreatly/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Grafanas returns a GrafanaInformer.
	Grafanas() GrafanaInformer
	// GrafanaDashboards returns a GrafanaDashboardInformer.
	GrafanaDashboards() GrafanaDashboardInformer
	// GrafanaDataSources returns a GrafanaDataSourceInformer.
	GrafanaDataSources() GrafanaDataSourceInformer
	// GrafanaFolders returns a GrafanaFolderInformer.
	GrafanaFolders() GrafanaFolderInformer
	// GrafanaNotificationChannels returns a GrafanaNotificationChannelInformer.
	GrafanaNotificationChannels() GrafanaNotificationChannelInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Grafanas returns a GrafanaInformer.
func (v *version) Grafanas() GrafanaInformer {
	return &grafanaInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GrafanaDashboards returns a GrafanaDashboardInformer.
func (v *version) GrafanaDashboards() GrafanaDashboardInformer {
	return &grafanaDashboardInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GrafanaDataSources returns a GrafanaDataSourceInformer.
func (v *version) GrafanaDataSources() GrafanaDataSourceInformer {
	return &grafanaDataSourceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GrafanaFolders returns a GrafanaFolderInformer.
func (v *version) GrafanaFolders() GrafanaFolderInformer {
	return &grafanaFolderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GrafanaNotificationChannels returns a GrafanaNotificationChannelInformer.
func (v *version) GrafanaNotificationChannels() GrafanaNotificationChannelInformer {
	return &grafanaNotificationChannelInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
