apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla-operator-multiregion
  namespace: scylla-operator-multiregion
  labels:
    app.kubernetes.io/name: scylla-operator-multiregion
    app.kubernetes.io/instance: scylla-operator-multiregion
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla-operator-multiregion
      app.kubernetes.io/instance: scylla-operator-multiregion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scylla-operator-multiregion
        app.kubernetes.io/instance: scylla-operator-multiregion
    spec:
      serviceAccountName: scylla-operator-multiregion
      containers:
      - name: scylla-operator
        image: docker.io/scylladb/scylla-operator:latest
        imagePullPolicy: IfNotPresent
        args:
        - operator-multiregion
        - --loglevel=2
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: scylla-operator-multiregion
                  app.kubernetes.io/name: scylla-operator-multiregion
              topologyKey: kubernetes.io/hostname
            weight: 1
