# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: alternator

---

# ServiceAccount for scylla members.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alternator-cluster-member
  namespace: alternator

---

# RoleBinding for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alternator-cluster-member
  namespace: alternator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scyllacluster-member
subjects:
  - kind: ServiceAccount
    name: alternator-cluster-member
    namespace: alternator

---

# Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: alternator-cluster
  namespace: alternator
spec:
  version: 4.4.5
  agentVersion: 2.5.1
  cpuset: true
  network:
    hostNetworking: true
  alternator:
    port: 8000
    writeIsolation: always
  sysctls:
  - "fs.aio-max-nr=30000000"
  datacenter:
    name: us-east-1
    racks:
    - name: a
      members: 1
      storage:
        storageClassName: local-raid-disks
        capacity: 1500G
      resources:
        limits:
          cpu: 7
          memory: 56G
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                    - us-east-1a
                - key: pool
                  operator: In
                  values:
                  - alternator-pool
        tolerations:
          - key: role
            operator: Equal
            value: scylla-clusters
            effect: NoSchedule
    - name: b
      members: 1
      storage:
        storageClassName: local-raid-disks
        capacity: 1500G
      resources:
        limits:
          cpu: 7
          memory: 56G
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-east-1b
              - key: pool
                operator: In
                values:
                - alternator-pool
        tolerations:
        - key: role
          operator: Equal
          value: scylla-clusters
          effect: NoSchedule
    - name: c
      members: 1
      storage:
        storageClassName: local-raid-disks
        capacity: 1500G
      resources:
        limits:
          cpu: 7
          memory: 56G
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-east-1c
              - key: pool
                operator: In
                values:
                - alternator-pool
        tolerations:
        - key: role
          operator: Equal
          value: scylla-clusters
          effect: NoSchedule
