apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-0
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:4.4.5
        command:
        - "/bin/bash"
        - "-c"
        - 'cassandra-stress write no-warmup n=100000000 cl=ONE -node "scylla-cluster-us-east-1-c-0.scylla.svc" -mode native cql3 connectionsPerHost=3 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=1..100000000 -rate threads=150  -log file=/cassandra-stress.load.data -schema "replication(factor=1)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 7
            memory: 14G
      restartPolicy: Never
      tolerations:
      - key: role
        operator: Equal
        value: application
        effect: NoSchedule
      nodeSelector:
        pool: "application-pool"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-1
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:4.4.5
        command:
        - "/bin/bash"
        - "-c"
        - 'cassandra-stress write no-warmup n=100000000 cl=ONE -node "scylla-cluster-us-east-1-c-0.scylla.svc" -mode native cql3 connectionsPerHost=3 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=100000001..200000000 -rate threads=150  -log file=/cassandra-stress.load.data -schema "replication(factor=1)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 7
            memory: 14G
      restartPolicy: Never
      tolerations:
      - key: role
        operator: Equal
        value: application
        effect: NoSchedule
      nodeSelector:
        pool: "application-pool"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-2
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:4.4.5
        command:
        - "/bin/bash"
        - "-c"
        - 'cassandra-stress write no-warmup n=100000000 cl=ONE -node "scylla-cluster-us-east-1-c-0.scylla.svc" -mode native cql3 connectionsPerHost=3 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=200000001..300000000 -rate threads=150  -log file=/cassandra-stress.load.data -schema "replication(factor=1)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 7
            memory: 14G
      restartPolicy: Never
      tolerations:
      - key: role
        operator: Equal
        value: application
        effect: NoSchedule
      nodeSelector:
        pool: "application-pool"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-stress-3
  labels:
    app: cassandra-stress
spec:
  template:
    spec:
      containers:
      - name: cassandra-stress
        image: scylladb/scylla:4.4.5
        command:
        - "/bin/bash"
        - "-c"
        - 'cassandra-stress write no-warmup n=100000000 cl=ONE -node "scylla-cluster-us-east-1-c-0.scylla.svc" -mode native cql3 connectionsPerHost=3 -col n=FIXED\(5\) size=FIXED\(64\)  -pop seq=300000001..400000000 -rate threads=150  -log file=/cassandra-stress.load.data -schema "replication(factor=1)" -errors ignore; cat /cassandra-stress.load.data'
        resources:
          limits:
            cpu: 7
            memory: 14G
      restartPolicy: Never
      tolerations:
      - key: role
        operator: Equal
        value: application
        effect: NoSchedule
      nodeSelector:
        pool: "application-pool"
---
