apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <eks_cluster_name>
  region: <eks_region>

availabilityZones:
- <eks_zone>

nodeGroups:
- name: scylla-pool
  instanceType: i3.2xlarge
  desiredCapacity: 3
  labels:
    pool: "scylla-pool"
  taints:
    role: "scylla-clusters:NoSchedule"
  tags:
    keep: alive
  ssh:
    allow: true
  kubeletExtraConfig:
    cpuManagerPolicy: static
  availabilityZones:
  - <eks_zone>

- name: alternator-pool
  instanceType: i3.2xlarge
  desiredCapacity: 3
  labels:
    pool: "alternator-pool"
  taints:
    role: "scylla-clusters:NoSchedule"
  tags:
    keep: alive
  ssh:
    allow: true
  kubeletExtraConfig:
    cpuManagerPolicy: static
  availabilityZones:
  - <eks_zone>

- name: apps-pool
  instanceType: c4.2xlarge
  desiredCapacity: 4
  labels:
    pool: "application-pool"
  taints:
    role: "application:NoSchedule"
  tags:
    keep: alive
  ssh:
    allow: true
  preBootstrapCommands:
  - curl -o /etc/yum.repos.d/scylla.repo -L http://repositories.scylladb.com/scylla/repo/3e3ec6ec-92b2-46ec-b64f-5b2338bc47de/centos/scylladb-4.0.repo
  - yum install -y scylla-tools

- name: utilities-pool
  instanceType: i3.large
  desiredCapacity: 1
  tags:
    keep: alive
  labels:
    pool: "utilities-pool"
  ssh:
    allow: true
