apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Etc/UTC"
  SERVERPORT: "51820"
  PEERS: "1"
  PEERDNS: "1.1.1.1"
  ALLOWEDIPS: "0.0.0.0/0"
  INTERNAL_SUBNET: "100.64.0.0/10"
