// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type GrafanaExpansion interface{}

type GrafanaDashboardExpansion interface{}

type GrafanaDataSourceExpansion interface{}

type GrafanaFolderExpansion interface{}

type GrafanaNotificationChannelExpansion interface{}
