// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/scylladb/scylla-operator/pkg/externalapi/integreatly/v1alpha1"
	scheme "github.com/scylladb/scylla-operator/pkg/externalclient/integreatly/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GrafanaDataSourcesGetter has a method to return a GrafanaDataSourceInterface.
// A group's client should implement this interface.
type GrafanaDataSourcesGetter interface {
	GrafanaDataSources(namespace string) GrafanaDataSourceInterface
}

// GrafanaDataSourceInterface has methods to work with GrafanaDataSource resources.
type GrafanaDataSourceInterface interface {
	Create(ctx context.Context, grafanaDataSource *v1alpha1.GrafanaDataSource, opts v1.CreateOptions) (*v1alpha1.GrafanaDataSource, error)
	Update(ctx context.Context, grafanaDataSource *v1alpha1.GrafanaDataSource, opts v1.UpdateOptions) (*v1alpha1.GrafanaDataSource, error)
	UpdateStatus(ctx context.Context, grafanaDataSource *v1alpha1.GrafanaDataSource, opts v1.UpdateOptions) (*v1alpha1.GrafanaDataSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GrafanaDataSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GrafanaDataSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GrafanaDataSource, err error)
	GrafanaDataSourceExpansion
}

// grafanaDataSources implements GrafanaDataSourceInterface
type grafanaDataSources struct {
	client rest.Interface
	ns     string
}

// newGrafanaDataSources returns a GrafanaDataSources
func newGrafanaDataSources(c *IntegreatlyV1alpha1Client, namespace string) *grafanaDataSources {
	return &grafanaDataSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the grafanaDataSource, and returns the corresponding grafanaDataSource object, and an error if there is any.
func (c *grafanaDataSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GrafanaDataSource, err error) {
	result = &v1alpha1.GrafanaDataSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grafanadatasources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GrafanaDataSources that match those selectors.
func (c *grafanaDataSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GrafanaDataSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GrafanaDataSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grafanadatasources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested grafanaDataSources.
func (c *grafanaDataSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("grafanadatasources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a grafanaDataSource and creates it.  Returns the server's representation of the grafanaDataSource, and an error, if there is any.
func (c *grafanaDataSources) Create(ctx context.Context, grafanaDataSource *v1alpha1.GrafanaDataSource, opts v1.CreateOptions) (result *v1alpha1.GrafanaDataSource, err error) {
	result = &v1alpha1.GrafanaDataSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("grafanadatasources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grafanaDataSource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a grafanaDataSource and updates it. Returns the server's representation of the grafanaDataSource, and an error, if there is any.
func (c *grafanaDataSources) Update(ctx context.Context, grafanaDataSource *v1alpha1.GrafanaDataSource, opts v1.UpdateOptions) (result *v1alpha1.GrafanaDataSource, err error) {
	result = &v1alpha1.GrafanaDataSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grafanadatasources").
		Name(grafanaDataSource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grafanaDataSource).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *grafanaDataSources) UpdateStatus(ctx context.Context, grafanaDataSource *v1alpha1.GrafanaDataSource, opts v1.UpdateOptions) (result *v1alpha1.GrafanaDataSource, err error) {
	result = &v1alpha1.GrafanaDataSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grafanadatasources").
		Name(grafanaDataSource.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grafanaDataSource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the grafanaDataSource and deletes it. Returns an error if one occurs.
func (c *grafanaDataSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grafanadatasources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *grafanaDataSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grafanadatasources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched grafanaDataSource.
func (c *grafanaDataSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GrafanaDataSource, err error) {
	result = &v1alpha1.GrafanaDataSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("grafanadatasources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
