// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/scylladb/scylla-operator/pkg/externalapi/integreatly/v1alpha1"
	scheme "github.com/scylladb/scylla-operator/pkg/externalclient/integreatly/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GrafanasGetter has a method to return a GrafanaInterface.
// A group's client should implement this interface.
type GrafanasGetter interface {
	Grafanas(namespace string) GrafanaInterface
}

// GrafanaInterface has methods to work with Grafana resources.
type GrafanaInterface interface {
	Create(ctx context.Context, grafana *v1alpha1.Grafana, opts v1.CreateOptions) (*v1alpha1.Grafana, error)
	Update(ctx context.Context, grafana *v1alpha1.Grafana, opts v1.UpdateOptions) (*v1alpha1.Grafana, error)
	UpdateStatus(ctx context.Context, grafana *v1alpha1.Grafana, opts v1.UpdateOptions) (*v1alpha1.Grafana, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Grafana, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GrafanaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Grafana, err error)
	GrafanaExpansion
}

// grafanas implements GrafanaInterface
type grafanas struct {
	client rest.Interface
	ns     string
}

// newGrafanas returns a Grafanas
func newGrafanas(c *IntegreatlyV1alpha1Client, namespace string) *grafanas {
	return &grafanas{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the grafana, and returns the corresponding grafana object, and an error if there is any.
func (c *grafanas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Grafana, err error) {
	result = &v1alpha1.Grafana{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grafanas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Grafanas that match those selectors.
func (c *grafanas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GrafanaList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GrafanaList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grafanas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested grafanas.
func (c *grafanas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("grafanas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a grafana and creates it.  Returns the server's representation of the grafana, and an error, if there is any.
func (c *grafanas) Create(ctx context.Context, grafana *v1alpha1.Grafana, opts v1.CreateOptions) (result *v1alpha1.Grafana, err error) {
	result = &v1alpha1.Grafana{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("grafanas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grafana).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a grafana and updates it. Returns the server's representation of the grafana, and an error, if there is any.
func (c *grafanas) Update(ctx context.Context, grafana *v1alpha1.Grafana, opts v1.UpdateOptions) (result *v1alpha1.Grafana, err error) {
	result = &v1alpha1.Grafana{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grafanas").
		Name(grafana.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grafana).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *grafanas) UpdateStatus(ctx context.Context, grafana *v1alpha1.Grafana, opts v1.UpdateOptions) (result *v1alpha1.Grafana, err error) {
	result = &v1alpha1.Grafana{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grafanas").
		Name(grafana.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grafana).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the grafana and deletes it. Returns an error if one occurs.
func (c *grafanas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grafanas").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *grafanas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grafanas").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched grafana.
func (c *grafanas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Grafana, err error) {
	result = &v1alpha1.Grafana{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("grafanas").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
