// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"net/http"

	v1alpha1 "github.com/scylladb/scylla-operator/pkg/externalapi/integreatly/v1alpha1"
	"github.com/scylladb/scylla-operator/pkg/externalclient/integreatly/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type IntegreatlyV1alpha1Interface interface {
	RESTClient() rest.Interface
	GrafanasGetter
	GrafanaDashboardsGetter
	GrafanaDataSourcesGetter
	GrafanaFoldersGetter
	GrafanaNotificationChannelsGetter
}

// IntegreatlyV1alpha1Client is used to interact with features provided by the integreatly.org group.
type IntegreatlyV1alpha1Client struct {
	restClient rest.Interface
}

func (c *IntegreatlyV1alpha1Client) Grafanas(namespace string) GrafanaInterface {
	return newGrafanas(c, namespace)
}

func (c *IntegreatlyV1alpha1Client) GrafanaDashboards(namespace string) GrafanaDashboardInterface {
	return newGrafanaDashboards(c, namespace)
}

func (c *IntegreatlyV1alpha1Client) GrafanaDataSources(namespace string) GrafanaDataSourceInterface {
	return newGrafanaDataSources(c, namespace)
}

func (c *IntegreatlyV1alpha1Client) GrafanaFolders(namespace string) GrafanaFolderInterface {
	return newGrafanaFolders(c, namespace)
}

func (c *IntegreatlyV1alpha1Client) GrafanaNotificationChannels(namespace string) GrafanaNotificationChannelInterface {
	return newGrafanaNotificationChannels(c, namespace)
}

// NewForConfig creates a new IntegreatlyV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*IntegreatlyV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new IntegreatlyV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*IntegreatlyV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &IntegreatlyV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new IntegreatlyV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *IntegreatlyV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new IntegreatlyV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *IntegreatlyV1alpha1Client {
	return &IntegreatlyV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *IntegreatlyV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
