apiVersion: scylla.scylladb.com/v1alpha1
kind: NodeConfig
metadata:
  name: cluster
spec:
  placement:
    nodeSelector:
      pool: scylla-pool
    tolerations:
        - key: role
          operator: Equal
          value: scylla-clusters
          effect: NoSchedule
