apiVersion: scylla.scylladb.com/v1alpha1
kind: NodeConfig
metadata:
  name: cluster
spec:
  placement:
    tolerations:
    - key: role
      operator: Equal
      value: scylla-clusters
      effect: NoSchedule
    nodeSelector:
      scylla.scylladb.com/node-type: scylla
