apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scylla-manager-service-monitor
  namespace: scylla-manager
spec:
  jobLabel: "app"
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla-manager
  endpoints:
    - port: metrics
      metricRelabelings:
        - sourceLabels: [ host ]
          targetLabel: instance
          regex: (.*)
          replacement: ${1}
