// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/scylladb/scylla-operator/pkg/externalclient/integreatly/clientset/versioned/typed/integreatly/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIntegreatlyV1alpha1 struct {
	*testing.Fake
}

func (c *FakeIntegreatlyV1alpha1) Alertmanagers(namespace string) v1alpha1.AlertmanagerInterface {
	return &FakeAlertmanagers{c, namespace}
}

func (c *FakeIntegreatlyV1alpha1) PodMonitors(namespace string) v1alpha1.PodMonitorInterface {
	return &FakePodMonitors{c, namespace}
}

func (c *FakeIntegreatlyV1alpha1) Probes(namespace string) v1alpha1.ProbeInterface {
	return &FakeProbes{c, namespace}
}

func (c *FakeIntegreatlyV1alpha1) Prometheuses(namespace string) v1alpha1.PrometheusInterface {
	return &FakePrometheuses{c, namespace}
}

func (c *FakeIntegreatlyV1alpha1) PrometheusRules(namespace string) v1alpha1.PrometheusRuleInterface {
	return &FakePrometheusRules{c, namespace}
}

func (c *FakeIntegreatlyV1alpha1) ServiceMonitors(namespace string) v1alpha1.ServiceMonitorInterface {
	return &FakeServiceMonitors{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIntegreatlyV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
