// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/scylladb/scylla-operator/pkg/externalapi/integreatly/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGrafanaFolders implements GrafanaFolderInterface
type FakeGrafanaFolders struct {
	Fake *FakeIntegreatlyV1alpha1
	ns   string
}

var grafanafoldersResource = schema.GroupVersionResource{Group: "integreatly.org", Version: "v1alpha1", Resource: "grafanafolders"}

var grafanafoldersKind = schema.GroupVersionKind{Group: "integreatly.org", Version: "v1alpha1", Kind: "GrafanaFolder"}

// Get takes name of the grafanaFolder, and returns the corresponding grafanaFolder object, and an error if there is any.
func (c *FakeGrafanaFolders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GrafanaFolder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(grafanafoldersResource, c.ns, name), &v1alpha1.GrafanaFolder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaFolder), err
}

// List takes label and field selectors, and returns the list of GrafanaFolders that match those selectors.
func (c *FakeGrafanaFolders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GrafanaFolderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(grafanafoldersResource, grafanafoldersKind, c.ns, opts), &v1alpha1.GrafanaFolderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GrafanaFolderList{ListMeta: obj.(*v1alpha1.GrafanaFolderList).ListMeta}
	for _, item := range obj.(*v1alpha1.GrafanaFolderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested grafanaFolders.
func (c *FakeGrafanaFolders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(grafanafoldersResource, c.ns, opts))

}

// Create takes the representation of a grafanaFolder and creates it.  Returns the server's representation of the grafanaFolder, and an error, if there is any.
func (c *FakeGrafanaFolders) Create(ctx context.Context, grafanaFolder *v1alpha1.GrafanaFolder, opts v1.CreateOptions) (result *v1alpha1.GrafanaFolder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(grafanafoldersResource, c.ns, grafanaFolder), &v1alpha1.GrafanaFolder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaFolder), err
}

// Update takes the representation of a grafanaFolder and updates it. Returns the server's representation of the grafanaFolder, and an error, if there is any.
func (c *FakeGrafanaFolders) Update(ctx context.Context, grafanaFolder *v1alpha1.GrafanaFolder, opts v1.UpdateOptions) (result *v1alpha1.GrafanaFolder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(grafanafoldersResource, c.ns, grafanaFolder), &v1alpha1.GrafanaFolder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaFolder), err
}

// Delete takes name of the grafanaFolder and deletes it. Returns an error if one occurs.
func (c *FakeGrafanaFolders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(grafanafoldersResource, c.ns, name, opts), &v1alpha1.GrafanaFolder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGrafanaFolders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(grafanafoldersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GrafanaFolderList{})
	return err
}

// Patch applies the patch and returns the patched grafanaFolder.
func (c *FakeGrafanaFolders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GrafanaFolder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(grafanafoldersResource, c.ns, name, pt, data, subresources...), &v1alpha1.GrafanaFolder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaFolder), err
}
