// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/scylladb/scylla-operator/pkg/externalapi/integreatly/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGrafanaDataSources implements GrafanaDataSourceInterface
type FakeGrafanaDataSources struct {
	Fake *FakeIntegreatlyV1alpha1
	ns   string
}

var grafanadatasourcesResource = schema.GroupVersionResource{Group: "integreatly.org", Version: "v1alpha1", Resource: "grafanadatasources"}

var grafanadatasourcesKind = schema.GroupVersionKind{Group: "integreatly.org", Version: "v1alpha1", Kind: "GrafanaDataSource"}

// Get takes name of the grafanaDataSource, and returns the corresponding grafanaDataSource object, and an error if there is any.
func (c *FakeGrafanaDataSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GrafanaDataSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(grafanadatasourcesResource, c.ns, name), &v1alpha1.GrafanaDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaDataSource), err
}

// List takes label and field selectors, and returns the list of GrafanaDataSources that match those selectors.
func (c *FakeGrafanaDataSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GrafanaDataSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(grafanadatasourcesResource, grafanadatasourcesKind, c.ns, opts), &v1alpha1.GrafanaDataSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GrafanaDataSourceList{ListMeta: obj.(*v1alpha1.GrafanaDataSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.GrafanaDataSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested grafanaDataSources.
func (c *FakeGrafanaDataSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(grafanadatasourcesResource, c.ns, opts))

}

// Create takes the representation of a grafanaDataSource and creates it.  Returns the server's representation of the grafanaDataSource, and an error, if there is any.
func (c *FakeGrafanaDataSources) Create(ctx context.Context, grafanaDataSource *v1alpha1.GrafanaDataSource, opts v1.CreateOptions) (result *v1alpha1.GrafanaDataSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(grafanadatasourcesResource, c.ns, grafanaDataSource), &v1alpha1.GrafanaDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaDataSource), err
}

// Update takes the representation of a grafanaDataSource and updates it. Returns the server's representation of the grafanaDataSource, and an error, if there is any.
func (c *FakeGrafanaDataSources) Update(ctx context.Context, grafanaDataSource *v1alpha1.GrafanaDataSource, opts v1.UpdateOptions) (result *v1alpha1.GrafanaDataSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(grafanadatasourcesResource, c.ns, grafanaDataSource), &v1alpha1.GrafanaDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaDataSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGrafanaDataSources) UpdateStatus(ctx context.Context, grafanaDataSource *v1alpha1.GrafanaDataSource, opts v1.UpdateOptions) (*v1alpha1.GrafanaDataSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(grafanadatasourcesResource, "status", c.ns, grafanaDataSource), &v1alpha1.GrafanaDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaDataSource), err
}

// Delete takes name of the grafanaDataSource and deletes it. Returns an error if one occurs.
func (c *FakeGrafanaDataSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(grafanadatasourcesResource, c.ns, name, opts), &v1alpha1.GrafanaDataSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGrafanaDataSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(grafanadatasourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GrafanaDataSourceList{})
	return err
}

// Patch applies the patch and returns the patched grafanaDataSource.
func (c *FakeGrafanaDataSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GrafanaDataSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(grafanadatasourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.GrafanaDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaDataSource), err
}
