// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/scylladb/scylla-operator/pkg/externalclient/integreatly/clientset/versioned/typed/integreatly/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIntegreatlyV1alpha1 struct {
	*testing.Fake
}

func (c *FakeIntegreatlyV1alpha1) Grafanas(namespace string) v1alpha1.GrafanaInterface {
	return &FakeGrafanas{c, namespace}
}

func (c *FakeIntegreatlyV1alpha1) GrafanaDashboards(namespace string) v1alpha1.GrafanaDashboardInterface {
	return &FakeGrafanaDashboards{c, namespace}
}

func (c *FakeIntegreatlyV1alpha1) GrafanaDataSources(namespace string) v1alpha1.GrafanaDataSourceInterface {
	return &FakeGrafanaDataSources{c, namespace}
}

func (c *FakeIntegreatlyV1alpha1) GrafanaFolders(namespace string) v1alpha1.GrafanaFolderInterface {
	return &FakeGrafanaFolders{c, namespace}
}

func (c *FakeIntegreatlyV1alpha1) GrafanaNotificationChannels(namespace string) v1alpha1.GrafanaNotificationChannelInterface {
	return &FakeGrafanaNotificationChannels{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIntegreatlyV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
