// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/scylladb/scylla-operator/pkg/externalapi/integreatly/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGrafanaNotificationChannels implements GrafanaNotificationChannelInterface
type FakeGrafanaNotificationChannels struct {
	Fake *FakeIntegreatlyV1alpha1
	ns   string
}

var grafananotificationchannelsResource = schema.GroupVersionResource{Group: "integreatly.org", Version: "v1alpha1", Resource: "grafananotificationchannels"}

var grafananotificationchannelsKind = schema.GroupVersionKind{Group: "integreatly.org", Version: "v1alpha1", Kind: "GrafanaNotificationChannel"}

// Get takes name of the grafanaNotificationChannel, and returns the corresponding grafanaNotificationChannel object, and an error if there is any.
func (c *FakeGrafanaNotificationChannels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GrafanaNotificationChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(grafananotificationchannelsResource, c.ns, name), &v1alpha1.GrafanaNotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaNotificationChannel), err
}

// List takes label and field selectors, and returns the list of GrafanaNotificationChannels that match those selectors.
func (c *FakeGrafanaNotificationChannels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GrafanaNotificationChannelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(grafananotificationchannelsResource, grafananotificationchannelsKind, c.ns, opts), &v1alpha1.GrafanaNotificationChannelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GrafanaNotificationChannelList{ListMeta: obj.(*v1alpha1.GrafanaNotificationChannelList).ListMeta}
	for _, item := range obj.(*v1alpha1.GrafanaNotificationChannelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested grafanaNotificationChannels.
func (c *FakeGrafanaNotificationChannels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(grafananotificationchannelsResource, c.ns, opts))

}

// Create takes the representation of a grafanaNotificationChannel and creates it.  Returns the server's representation of the grafanaNotificationChannel, and an error, if there is any.
func (c *FakeGrafanaNotificationChannels) Create(ctx context.Context, grafanaNotificationChannel *v1alpha1.GrafanaNotificationChannel, opts v1.CreateOptions) (result *v1alpha1.GrafanaNotificationChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(grafananotificationchannelsResource, c.ns, grafanaNotificationChannel), &v1alpha1.GrafanaNotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaNotificationChannel), err
}

// Update takes the representation of a grafanaNotificationChannel and updates it. Returns the server's representation of the grafanaNotificationChannel, and an error, if there is any.
func (c *FakeGrafanaNotificationChannels) Update(ctx context.Context, grafanaNotificationChannel *v1alpha1.GrafanaNotificationChannel, opts v1.UpdateOptions) (result *v1alpha1.GrafanaNotificationChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(grafananotificationchannelsResource, c.ns, grafanaNotificationChannel), &v1alpha1.GrafanaNotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaNotificationChannel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGrafanaNotificationChannels) UpdateStatus(ctx context.Context, grafanaNotificationChannel *v1alpha1.GrafanaNotificationChannel, opts v1.UpdateOptions) (*v1alpha1.GrafanaNotificationChannel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(grafananotificationchannelsResource, "status", c.ns, grafanaNotificationChannel), &v1alpha1.GrafanaNotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaNotificationChannel), err
}

// Delete takes name of the grafanaNotificationChannel and deletes it. Returns an error if one occurs.
func (c *FakeGrafanaNotificationChannels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(grafananotificationchannelsResource, c.ns, name, opts), &v1alpha1.GrafanaNotificationChannel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGrafanaNotificationChannels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(grafananotificationchannelsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GrafanaNotificationChannelList{})
	return err
}

// Patch applies the patch and returns the patched grafanaNotificationChannel.
func (c *FakeGrafanaNotificationChannels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GrafanaNotificationChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(grafananotificationchannelsResource, c.ns, name, pt, data, subresources...), &v1alpha1.GrafanaNotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GrafanaNotificationChannel), err
}
