apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scylladb:aggregate-to-scyllacluster-member
  labels:
    rbac.operator.scylladb.com/aggregate-to-scylla-member: "true"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - watch
# Sidecar no longer fetches ScyllaClusters. Necessary information is provided by the Operator to sidecar via ScyllaDB config or arguments.
# However, to ensure smooth Operator updates, this cannot be removed earlier than in 1.16.
# TODO: remove this permission in Operator >=1.16 (https://github.com/scylladb/scylla-operator/issues/2141)
- apiGroups:
  - scylla.scylladb.com
  resources:
  - scyllaclusters
  verbs:
  - get
