# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla

---

# ServiceAccount for scylla members.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-cluster-member
  namespace: scylla

---

# RoleBinding for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simple-cluster-member
  namespace: scylla
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scyllacluster-member
subjects:
  - kind: ServiceAccount
    name: simple-cluster-member
    namespace: scylla

---

# Simple Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: simple-cluster
  namespace: scylla
spec:
  version: 4.5.1
  agentVersion: 2.5.2
  developerMode: true
  datacenter:
    name: us-east-1
    racks:
      - name: us-east-1a
        members: 1
        storage:
          capacity: 10Gi
        resources:
          limits:
            cpu: 1
            memory: 2Gi