# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla

---

# Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  version: 5.0.0
  agentVersion: 3.0.0
  cpuset: true
  sysctls:
  - "fs.aio-max-nr=6097152"
  dnsDomains:
  - scylla-cluster.scylla.apps.serverless-demo.us-east-1.eks.k8s.dev.scylla-operator.scylladb.com
  exposeOptions:
    cql:
      ingress:
        annotations:
          haproxy.org/ssl-passthrough: "true"
        ingressClassName: haproxy
  datacenter:
    name: us-east-1
    racks:
    - name: a
      members: 3
      storage:
        capacity: 50G
      resources:
        limits:
          cpu: 1
          memory: 4G
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: pool
                  operator: In
                  values:
                    - scylla-pool
        tolerations:
          - key: role
            operator: Equal
            value: scylla-clusters
            effect: NoSchedule