# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla

---

# ServiceAccount for scylla members.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scylla-cluster-member
  namespace: scylla

---

# RoleBinding for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scylla-cluster-member
  namespace: scylla
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scyllacluster-member
subjects:
  - kind: ServiceAccount
    name: scylla-cluster-member
    namespace: scylla

---

# Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  version: 4.4.1
  agentVersion: 2.5.1
  cpuset: true
  network:
    hostNetworking: true
  sysctls:
  - "fs.aio-max-nr=30000000"
  datacenter:
    name: us-east-1
    racks:
    - name: a
      members: 3
      storage:
        storageClassName: local-raid-disks
        capacity: 1800G
      agentResources:
        limits:
          cpu: 200m
          memory: 2G
      resources:
        limits:
          cpu: 14
          memory: 112G
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: pool
                  operator: In
                  values:
                    - scylla-pool
        tolerations:
          - key: role
            operator: Equal
            value: scylla-clusters
            effect: NoSchedule
