apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: serverless-demo
  region: us-east-1

nodeGroups:
- name: scylla-pool
  instanceType: m5a.xlarge
  desiredCapacity: 3
  labels:
    pool: "scylla-pool"
  taints:
    role: "scylla-clusters:NoSchedule"
  tags:
    keep: alive
  ssh:
    allow: true
  kubeletExtraConfig:
    cpuManagerPolicy: static

- name: utilities-pool
  instanceType: c5a.xlarge
  desiredCapacity: 1
  labels:
    pool: "utilities-pool"
  tags:
    keep: alive
  ssh:
    allow: true
