apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <eks_cluster_name>
  region: <eks_region>

availabilityZones:
- <eks_zone>

nodeGroups:
- name: scylla-pool
  instanceType: i3.2xlarge
  desiredCapacity: 3
  labels:
    pool: "scylla-pool"
  tags:
    keep: "12"
  taints:
    role: "scylla-clusters:NoSchedule"
  ssh:
    allow: true
  kubeletExtraConfig:
    cpuManagerPolicy: static
  availabilityZones:
  - <eks_zone>

- name: cassandra-stress-pool
  instanceType: c4.2xlarge
  desiredCapacity: 4
  tags:
    keep: "12"
  labels:
    pool: "cassandra-stress-pool"
  taints:
    role: "cassandra-stress:NoSchedule"
  ssh:
    allow: true

- name: monitoring-pool
  instanceType: i3.large
  desiredCapacity: 1
  tags:
    keep: "12"
  labels:
    pool: "monitoring-pool"
  ssh:
    allow: true
